import React, { useEffect, useState } from 'react'
import type { BidProject } from './model'
import { pdfPhysicalPage, aiSourceIssue, type AiJob, type AiKind, type AiPrepared, type AiSettings, type PdfPageRange } from './ai-model'
const kinds:Record<AiKind,string>={requirements:'提取要求候选',outline:'建议章节目录',chapter:'起草章节候选'}
const states={running:'生成中',succeeded:'待人工核对',failed:'失败',canceled:'已取消',interrupted:'上次中断'}
export function AiPanel({bid,beforeAction,onApplied,onClose,onSource,lock,disabled}:{lock:(operation:Promise<void>|null)=>void;disabled:boolean;bid:BidProject;beforeAction:()=>Promise<boolean>;onApplied:(bid:BidProject)=>void;onClose:()=>void;onSource:(sourceId:string,location:string)=>void}){
  const api=window.workbench.bids.ai
  const [settings,setSettings]=useState<AiSettings|null>(null),[model,setModel]=useState(''),[key,setKey]=useState('')
  const [kind,setKind]=useState<AiKind>('requirements'),[sources,setSources]=useState<string[]>([]),[sectionId,setSectionId]=useState(bid.sections[0]?.id||'')
  const [jobs,setJobs]=useState<AiJob[]>([]),[prepared,setPrepared]=useState<AiPrepared|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const [selections,setSelections]=useState<Record<string,number[]>>({}),[pageRanges,setPageRanges]=useState<Record<string,PdfPageRange>>({})
  const refresh=async()=>setJobs(await api.list(bid.id))
  useEffect(()=>{let live=true;void api.settings().then(s=>{if(live){setSettings(s);setModel(s.model)}}).catch(e=>live&&setError(String(e)));void refresh().catch(e=>live&&setError(String(e)));return()=>{live=false}},[])
  useEffect(()=>{let live=true;void api.list(bid.id).then(items=>{if(live)setJobs(items)}).catch(e=>live&&setError(String(e)));return()=>{live=false}},[bid.id,bid.revision])
  useEffect(()=>{const token=prepared?.token;return()=>{if(token)void api.discard(token).catch(()=>{})}},[prepared?.token])
  useEffect(()=>{if(!jobs.some(j=>j.state==='running'))return;const timer=setInterval(()=>{void refresh().catch(e=>setError(String(e)))},1500);return()=>clearInterval(timer)},[jobs.some(j=>j.state==='running')])
  async function run(action:()=>Promise<void>){if(busy||disabled)return;const operation=(async()=>{setBusy(true);setError('');try{if(!(await beforeAction()))throw new Error('当前投标尚未保存，请先解决保存提示。');await action()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}})();lock(operation);try{await operation}finally{lock(null)}}
  return <section inert={disabled&&!busy} className="bid-card bid-ai-panel" aria-label="DeepSeek辅助">
    <div className="bid-toolbar"><h2>DeepSeek 辅助</h2><span>候选生成 · 人工核对后采纳</span><button className="bid-button" disabled={busy} onClick={onClose}>收起AI辅助</button></div>
    <details open={!settings?.hasKey}><summary>服务设置 · {settings?.hasKey?'已保存密钥':'未设置密钥'}</summary><fieldset className="bid-fieldset" disabled={busy}><div className="bid-form">
      <label className="bid-field"><span>模型名称</span><input value={model} onChange={e=>setModel(e.target.value)} placeholder="deepseek-flash"/><small>官方接口 api.deepseek.com；名称可按账户可用模型修改。</small></label>
      <label className="bid-field"><span>API密钥</span><input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder={settings?.hasKey?'留空保留现有密钥':'在本机填写，不要发到聊天'}/><small>Windows安全存储加密；不会写入投标备份或导出文件。</small></label>
    </div><div className="bid-toolbar"><button className="bid-button" onClick={()=>void run(async()=>{setSettings(await api.configure(model,key));setKey('')})}>保存AI设置</button>{settings?.hasKey&&<button className="bid-button" onClick={()=>void run(async()=>{setSettings(await api.configure(model,'',true));setKey('')})}>移除本机密钥</button>}</div></fieldset></details>
    <fieldset className="bid-fieldset" disabled={busy}>
      <div className="bid-form"><label className="bid-field"><span>本次任务</span><select value={kind} onChange={e=>setKind(e.target.value as AiKind)}>{Object.entries(kinds).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{kind==='chapter'&&<label className="bid-field"><span>参考章节</span><select value={sectionId} onChange={e=>setSectionId(e.target.value)}>{bid.sections.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>}</div>
      <h3>选择允许发送的资料</h3>{bid.sources.filter(s=>s.kind!=='证明材料').map(s=><label className="bid-check" key={s.id}><input type="checkbox" disabled={!s.blocks.length} checked={sources.includes(s.id)} onChange={e=>setSources(e.target.checked?[...sources,s.id]:sources.filter(id=>id!==s.id))}/>{s.name} · {s.blocks.length}段{s.warnings.length?' · 有解析提示，请核对原件':''}</label>)}
      {bid.sources.filter(s=>sources.includes(s.id)&&s.asset.endsWith('.pdf')).map(s=><div className="bid-card" key={s.id}><label className="bid-check"><input type="checkbox" checked={!!pageRanges[s.id]} onChange={e=>setPageRanges(current=>{const next={...current};if(e.target.checked)next[s.id]={from:1,to:Math.max(1,...s.blocks.map(b=>pdfPhysicalPage(b.location)??0))};else delete next[s.id];return next})}/>{s.name} · 只发送指定物理页</label>{pageRanges[s.id]&&<div className="bid-form"><label className="bid-field"><span>起始物理页</span><input type="number" min="1" max="500" value={pageRanges[s.id].from||''} onChange={e=>setPageRanges({...pageRanges,[s.id]:{...pageRanges[s.id],from:Number(e.target.value)}})}/></label><label className="bid-field"><span>结束物理页</span><input type="number" min="1" max="500" value={pageRanges[s.id].to||''} onChange={e=>setPageRanges({...pageRanges,[s.id]:{...pageRanges[s.id],to:Number(e.target.value)}})}/></label></div>}<small>从封面起按文件顺序计数；没有文字的页不执行OCR。超4万字符时请缩小页范围。</small></div>)}
      <p className="bid-notice">只发送所选资料的提取文字；目录/章节任务还会发送项目名称、地点、标段、期限，章节任务包含所选章节正文。下一步可查看完整发送内容。文字型PDF可按物理页选择；原始附件不上传，扫描页和图片尚未执行OCR。生成可能计费，实际金额以DeepSeek账单为准。</p>
      <button className="bid-button primary" disabled={!settings?.hasKey||!sources.length||jobs.some(j=>j.state==='running')} onClick={()=>void run(async()=>{setPrepared(await api.prepare({bidId:bid.id,kind,sourceIds:sources,sectionId:kind==='chapter'?sectionId:'',pageRanges:Object.fromEntries(Object.entries(pageRanges).filter(([id])=>sources.includes(id)))}))})}>预览本次发送内容</button>
    </fieldset>
    {error&&<p className="bid-danger" role="alert">{error}</p>}
    <h3>本标段任务记录</h3><p className="bid-muted">成功结果可重开后继续采纳；中断不会自动重发。投标备份仅包含已采纳内容，AI任务记录和密钥不会随备份迁移。</p>
    {jobs.map(job=>{const issue=job.state==='succeeded'?(aiSourceIssue(bid,job)||job.reviewIssue||''):'';const rows=job.kind==='requirements'?job.result?.requirements.map(r=>({title:r.title,text:r.reference.quote,references:[r.reference]})):job.kind==='outline'?job.result?.outline.map(r=>({title:r.title,text:r.reference.quote,references:[r.reference]})):job.result?.chapter?[{title:'章节草稿（新增候选章节，保留原正文）',text:job.result.chapter.body,references:job.result.chapter.references}]:[];return <details className="bid-ai-job" key={job.id} open={job.state==='running'}><summary>{kinds[job.kind]} · {issue?'来源待重新核对':states[job.state]} · {new Date(job.createdAt).toLocaleString()}</summary>
      <p className="bid-muted">模型：{job.model} · {job.pageRanges&&Object.entries(job.pageRanges).map(([id,r])=><span key={id}>{bid.sources.find(s=>s.id===id)?.name} · 物理页{r.from}—{r.to} · </span>)} {job.usage?`输入 ${job.usage.input} / 输出 ${job.usage.output} tokens`:'用量未返回；不代表未计费'}</p>{job.error&&<p className="bid-danger">{job.error}</p>}
      {issue&&<p className="bid-notice" role="status">{issue}</p>}
      {(rows??[]).map((r,i)=><div className="bid-candidate" key={i}><input aria-label={`选择候选：${r.title}`} type="checkbox" disabled={!!issue||job.applied.includes(i)||busy} checked={(selections[job.id]??[]).includes(i)&&!job.applied.includes(i)} onChange={e=>setSelections({...selections,[job.id]:e.target.checked?[...(selections[job.id]??[]),i]:(selections[job.id]??[]).filter(n=>n!==i)})}/><span><strong>{r.title}{job.applied.includes(i)?' · 已加入':''}</strong><span className="bid-candidate-text">{r.text}</span>{r.references.map((reference,n)=>{const source=bid.sources.find(s=>s.id===reference.sourceId),stamp=job.sourceContext?.find(s=>s.id===reference.sourceId),block=source?.blocks[reference.index],located=!!block?.text.includes(reference.quote);return <div className="bid-ai-reference" key={n}><small>来源：{stamp?.name||source?.name||'资料缺失'} · 版本：{stamp?.version||'未记录'} · {located?block!.location:'当前位置无法核对'}</small>{job.kind==='chapter'&&<span className="bid-candidate-text">{reference.quote}</span>}<button className="bid-text-button" disabled={busy||!located} onClick={()=>void run(async()=>onSource(reference.sourceId,block!.location))}>查看引用原文</button></div>})}</span></div>)}
      <div className="bid-toolbar">{job.state==='running'?<button className="bid-button" onClick={()=>void run(async()=>{await api.cancel(bid.id,job.id);await refresh()})}>取消此任务</button>:<><button className="bid-button" disabled={busy} onClick={()=>{setKind(job.kind);setSources(job.sourceIds.filter(id=>bid.sources.some(s=>s.id===id&&s.kind!=='证明材料')));setSectionId(bid.sections.some(s=>s.id===job.sectionId)?job.sectionId:bid.sections[0]?.id||'');setPageRanges(job.pageRanges??{});setError('已恢复任务选择；请重新预览发送范围后手动重试。')}}>按此任务重新准备</button><button className="bid-button" disabled={busy} onClick={()=>void run(async()=>{await api.remove(bid.id,job.id);await refresh()})}>移除任务记录</button></>}{job.state==='succeeded'&&<button className="bid-button primary" disabled={busy||!!issue||!(selections[job.id]??[]).some(i=>!job.applied.includes(i))} onClick={()=>void run(async()=>{const updated=await api.apply(bid.id,job.id,(selections[job.id]??[]).filter(i=>!job.applied.includes(i)));onApplied(updated);setSelections({...selections,[job.id]:[]});await refresh()})}>加入所选候选</button>}</div>
    </details>})}
    {prepared&&<div className="bid-modal-shade"><div className="bid-modal bid-ai-consent" role="dialog" aria-modal="true" aria-label="确认发送到DeepSeek"><h2>确认本次发送范围</h2><p>{prepared.provider} · {prepared.model}<br/>{prepared.characters}字符 · {kinds[kind]}；可能产生费用</p><textarea readOnly aria-label="本次发送内容" value={prepared.preview}/><p>以下操作将把上方文字发送给DeepSeek。资料中的指令仅作为数据处理；回复仍需专业核定。</p><div className="bid-toolbar"><button className="bid-button" disabled={busy} onClick={()=>void run(async()=>{await api.discard(prepared.token);setPrepared(null)})}>取消发送</button><button className="bid-button primary" disabled={busy} onClick={()=>void run(async()=>{await api.start(prepared.token,true);setPrepared(null);await refresh()})}>确认发送并生成</button></div>{error&&<p className="bid-danger">{error}</p>}</div></div>}
  </section>
}
